def display_time(time):
    hours, minutes = int(time[:2]), int(time[2:])
    
    # Convert hours and minutes to binary strings with leading zeros
    hour_tens = format(hours // 10, '04b')
    hour_ones = format(hours % 10, '04b')
    minute_tens = format(minutes // 10, '04b')
    minute_ones = format(minutes % 10, '04b')
    
    # Create the watch face display
    watch_face = [
        '  ' + ('*' if hour_tens[0] == '1' else '.') + ' ' + ('*' if minute_tens[0] == '1' else '.') + '  ',
        ' ' + ('*' if hour_tens[1] == '1' else '.') + ' ' + ('*' if minute_tens[1] == '1' else '.') + ' ',
        ' ' + ('*' if hour_tens[2] == '1' else '.') + ' ' + ('*' if minute_tens[2] == '1' else '.') + ' ',
        ('*' if hour_tens[3] == '1' else '.') + ' ' + ('*' if minute_tens[3] == '1' else '.') + ' ' + ('*' if hour_ones[0] == '1' else '.') + ' ',
        ('*' if hour_ones[1] == '1' else '.') + ' ' + ('*' if minute_ones[0] == '1' else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[1] == '1' else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[2] == '1' else '.') + ' ',
        ('*' if minute_ones[3] == '1' else '.') + ' ' + ('*' if hour_ones[1] == '1' else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[1] == '1' else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] == '1' else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[2] == '1' else '.') + ' ',
        ('*' if minute_ones[3] == '1' else '.') + ' ' + ('*' if hour_ones[0] == '1' else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] == '1' else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[1] == '1' else '.') + ' ',
        ('*' if hour_ones[1] == '1' else '.') + ' ' + ('*' if minute_ones[3] == '1' else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[2] == '1' else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] == '1' else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[2] == '1' else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[3] == '1' else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] == '1' else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[1] == '1' else '.') + ' ',
        ('*' if hour_ones[1] == '1' else '.') + ' ' + ('*' if minute_ones[3] == '1' else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[2] == '1' else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[1] else '.') + ' ',
        ('*' if hour_ones[1] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[1] else '.') + ' ',
        ('*' if hour_ones[1] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[1] else '.') + ' ',
        ('*' if hour_ones[1] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[1] else '.') + ' ',
        ('*' if hour_ones[1] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[1] else '.') + ' ',
        ('*' if hour_ones[1] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[1] else '.') + ' ',
        ('*' if hour_ones[1] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[1] else '.') + ' ',
        ('*' if hour_ones[1] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_ones[3] == '1' else '.') + ' ' + ('*' if minute_ones[1] else '.') + ' ',
        ('*' if hour_ones[1] == '1' else '.') + ' ' + ('*' if minute_ones[3] else '.') + ' ',
        ('*' if hour_ones[0] == '1' else '.') + ' ' + ('*' if minute_ones[2] else '.') + ' ',
        ('*' if hour_ones[2] == '1' else '.') + ' ' + ('*' if minute_ones[0] else '.') + ' ',
        ('*' if hour_